### ISSUE TITLE
Разрешение экрана для приложения

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#1]
От заказчика:
После того как сделаешь фотографию кнопки Сохранить и Отмена оказываются за пределами экрана и добраться до них нет возможности.

Какое в данный момент используется разрешение? Заказчик просит установить минимально возможное для современных телефонов, так как пользоваться им будут на самых дешевых смартфонах.

Имеется ли возможность использовать скролинг формы, если форма не влезает на экран?

**Comment by BishopGIS** [comment]
1. Кнопки может стоит вынести в actionbar? Тогда они будут всегда видны.
2. Скролить точно можно. Достаточно в layout добавить  scrollview или horisontalscrollview.

**Comment by NikitaFeodonit** [comment]
Проверил в эмуляторе с Android 4.2.2, часть экрана занимают экранные кнопки Back, Home, Recent.

При данной раскладке элементов более менее сносно работать при 240х320 и плотности точек, которое система определяет, как ldpi (120 dpi). В эмуляторе это могут быть размеры экрана с данным разрешением от 2.9", хотя реально именно 120 dpi имеется при размере 3.3". То есть, что 2.9", что 3.3" выглядят одинаково, только физические размеры пропорционально разные. Какой минимальный размер диагонали на реальных устройствах для данной плотности, я не знаю.

Если экран сделать меньше 2.9", то система для эмулятора уже выдает плотность экрана mdpi (160 dpi). Тогда элементы самого android'а (4.х) уже криво отображаются. Думаю, что для 4.х из "дешевых" таких не делали. А с нашим приложением при данной раскладке просто неудобно работать.

Для плотности mdpi (160 dpi) хорошим разрешением получается 320х480 при диагонали от 3.1" (реально 160 dpi имеет 3.6").
