### ISSUE TITLE
Оформление полей ввода

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#100]
Поля ввода данных предлагаю оформить как в приложенных скриншотах (сделаны в приложении Collector for ArcGIS)

![screenshot_2015-06-26-16-31-43 1](https://cloud.githubusercontent.com/assets/1277422/8392454/263fbf1a-1cf4-11e5-8987-4b91500fefb5.png)
![screenshot_2015-06-26-16-31-58](https://cloud.githubusercontent.com/assets/1277422/8392455/295ef68e-1cf4-11e5-96e4-fdc7037f2e9e.png)

**Comment by yellow-sky** [comment]
Пока не делать !!!!
Занес для истории

**Comment by NikitaFeodonit** [comment]
Выполнить получилось почти автоматически.
