### ISSUE TITLE
Оптимизировать фото для отправки

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#12]
Фото отснятое пользователем на любом устройстве должно приводится к разрешению 640х480

**Comment by NikitaFeodonit** [comment]
Из "Требования к мобильному приложению ГИС v2.docx":

> Передаваемые на сервер фотографии должны быть  в формате jpg, иметь размер 448х336 точек, горизонтальное и вертикальное разрешение 72 точек на дюйм

Что есть верно?

**Comment by yellow-sky** [comment]
Делаем, как было в ТЗ: 448х336

**Comment by BishopGIS** [comment]
Фотки ужимаются при передаче. а на устройстве остаются нормального размера или после съемки ужимаются сразу и уже всю дорогу ужатые?

**Comment by yellow-sky** [comment]
Предлагаю ужимать сразу. Место сэкономим и скорость отображения в галереи вырастет.
И при просмотре из галереи будет видно какая фотка уйдет на самом деле.

**Comment by NikitaFeodonit** [comment]
Фото 448х336 == 4х3. У меня аппарат снимает 2592х1456 == 16х9.

Если приводить к 4х3, то или обрезать по краям, или размеры полезного изображения будут 448х252, что довольно мало, как думаю.

Как быть?

**Comment by yellow-sky** [comment]
Обрезать фотографию при уменьшении нельзя, иначе можно потерять важную информацию. Предлагаю установить ограничение на размер фотографии по вертикали и горизонтали в 640 пикселей и уменьшать фотографию, сохраняя исходные пропорции, так, чтобы в итоге ее большая сторона стала 640 пикселей.

**Comment by NikitaFeodonit** [comment]
> Предлагаю ужимать сразу. Место сэкономим и скорость отображения в галереи вырастет.
> И при просмотре из галереи будет видно какая фотка уйдет на самом деле.

Сейчас получилось пока так: при фотографировании фото сохраняются в папке /sdcard/ngm_clink_monitoring (по ТЗ), после чего обрабатываются и нужного размера (640 x YYY) ужимаются с JPEG-качеством 75%, и в таком виде кладутся в базу слоев программы для отправки на сервер.

То есть пока есть две копии -- в папке на sdcard (никак не обработанные) и в базе слоев (обработанные).

Размер фото в базе 20-30 кб, размер оригинальных около 1 МБ.

При отображении в гелерее превьюшки для отображения формируются из фото в базе, где они малого размера, потому это происходит довольно быстро. На своем довольно мощном аппарате я заметил разницу отображения активити с тремя фото.

Получившийся вариант временный. У меня тут вопросы.

1) По ТЗ должна быть папка на sdcard. Для библиотеки для синхронизации фото должны быть в базе. Тут или дублирование данных, или нужно переопределять функции работы с фото в библиотеке на папку по ТЗ.

2) Если согласиться с дублированием, то можно оставлять фото в папке по ТЗ в оригинальном виде, может еще где клиенту пригодятся. Но тут немного сложнее обработка фото будет, например, при удалении. Нужно хранить соответствие файлов в базе и в папке по ТЗ для совместной обработки. При том в той папке должна быть своя структура, отличающаяся от структуры в базе.

> Место сэкономим и скорость отображения в галереи вырастет.

По скорости уже описал, по месту -- зависит от варианта сохранения оригинала фото.

> И при просмотре из галереи будет видно какая фотка уйдет на самом деле.

Тут можно любую показывать, оригинал или из базы.

**Comment by yellow-sky** [comment]
От клиента:
Предлагаю сделать так, чтобы пользователь в настройках программы мог выбирать сохранять полноразмерные копии (дубли) фотографий или нет, а также указывать папку, в которой они будут сохраняться. 
По умолчанию, сохранение полноразмерных копий должно быть отключено. Если пользователь включил опцию сохранения полноразмерных копий фотографий и в какой-то момент место на карте памяти закончилось, то программа должна продолжать работать без сохранения полноразмерных копий (предварительно проинформировав пользователя в виде всплывающего уведомления).

**Comment by yellow-sky** [comment]
Мои комментарии:

> Тут или дублирование данных, или нужно переопределять функции работы с фото в 
> библиотеке на папку по ТЗ.

Нужно дублирование.

> Но тут немного сложнее обработка фото будет, например, при удалении. Нужно хранить 
> соответствие файлов в базе и в папке по ТЗ для совместной обработки. При том в той папке 
> должна быть своя структура, отличающаяся от структуры в базе.

Синхронизировать полноразмерные фото на SD-карте c сервером не нужно! Они пишутся и навсегда остаются там, пока пользователь сам их не удалит.

**Comment by NikitaFeodonit** [comment]
> Синхронизировать полноразмерные фото на SD-карте c сервером не нужно! Они пишутся и навсегда остаются там, пока пользователь сам их не удалит.

А как быть с этим (из #15):

> Так же необходима возможность удаления фото из ранее сделанных.

То есть, что именно должно тогда удалятся через программу?

**Comment by yellow-sky** [comment]
Должна удаляться наша сжатая. А большая пусть так и лежит.
Эти пункты относятся к синхронизируемым.

Если не сложно и не займет времени, можно сделать удаление и больших. Но
мне кажется это лишняя работа.

25 марта 2015 г., 14:08 пользователь NikitaFeodonit <
notifications@github.com> написал:

> Синхронизировать полноразмерные фото на SD-карте c сервером не нужно! Они
> пишутся и навсегда остаются там, пока пользователь сам их не удалит.
> 
> А как быть с этим (из #15
> https://github.com/nextgis/ngm_clink_monitoring/issues/15):
> 
> Так же необходима возможность удаления фото из ранее сделанных.
> 
> То есть, что именно должно тогда удалятся через программу?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/12#issuecomment-85984530
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
Собственно, оптимизация фото сделана. Остальное, что тут обсуждали, вынес в отдельные issues, потому этот закрываю.
