### ISSUE TITLE
Кнопки в диалоговых окнах

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#121]
У нас выводится одна или две кнопки.
Предлагается всегда выводить две, при необходимости одну скрывать.

Кнопки должны быть именно кнопками, а не надписями, как сейчас. На солнце надписи не видны.

**Comment by NikitaFeodonit** [comment]
> На солнце надписи не видны.

Осталось только это, но будет менятся вместе со всем оформлением приложения, потому закрываю.
