### ISSUE TITLE
Зацикленный процесс определения координат

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#124]
Если в результате определения время заканчивается а координат нет, предлагается:
1) В первый раз вывести диал окно с сообщением "Координаты не моугт быть определены. Пожалуйста измените Ваше местоположение и попробуйте еще" с одной кнопкой - ОК.
2) Перезапускать цикл определения координат.

!!! Проверить, что будет если это окно будет появляться во время фотографирования

**Comment by NikitaFeodonit** [comment]
> Проверить, что будет если это окно будет появляться во время фотографирования

Диалог появится по возвращении в приложение.
