### ISSUE TITLE
Кривая форма

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#127]
Иногда, при неизвестных обстоятельствах выводятся кривые формы:
![screenshot_2015-07-01-13-50-26](https://cloud.githubusercontent.com/assets/1277422/8459253/a669ed36-2024-11e5-9c82-8eab59413b90.png)
![screenshot_2015-07-01-12-16-04](https://cloud.githubusercontent.com/assets/1277422/8459257/afd91bda-2024-11e5-9ed7-e3ce69e0a4cc.png)

**Comment by NikitaFeodonit** [comment]
Как я понял, не выводится название линии связи. На каких данных это проявляется, на всех или только определенных?

**Comment by yellow-sky** [comment]
В ходе вчерашних опытов выяснились подробности.
Да, нет названия линии связи и других полей, в зависимости от того, какая из форм была открыта. Происходит это, если приложение было свернуто, прошла синхронизация, и после этого приложение снова развернули.

**Comment by yellow-sky** [comment]
https://github.com/nextgis/ngm_clink_monitoring/issues/127#issuecomment-118515022

4 июля 2015 г., 17:05 пользователь NikitaFeodonit notifications@github.com
написал:

> Как я понял, не выводится название линии связи. На каких данных это
> проявляется, на всех или только определенных?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/127#issuecomment-118515022
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
У меня не повторяется.

**Comment by NikitaFeodonit** [comment]
Скорее всего из-за #163, который закрыл. Понаблюдаем, будет ли повторение теперь.
