### ISSUE TITLE
Проводить синхронизацию как при доступности Wi-Fi, так и GPRS

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#13]
Синхронизировать данные и фото постоянно - при WiFi и GPRS.
Можно сделать настройку - синхронизировать фото только когда есть Wifi. Но она должна быть включена по умолчанию.

**Comment by NikitaFeodonit** [comment]
> Синхронизировать данные и фото постоянно - при WiFi и GPRS.
> Можно сделать настройку - синхронизировать фото только когда есть Wifi. Но она должна быть включена по умолчанию.

Что я понял.

Должна быть настройка "Синхронизировать фото только через WiFi", которая должна быть в**Ы**ключена (отключена) по-умолчанию. Если она включена, то через GPRS фото не должны синхронизироваться.

Всё остальное должно синхронизироваться при наличии любого вида связи.

Верно?

**Comment by yellow-sky** [comment]
Да, все верно. Предлагаю реализовывать данную функцию в android_maplib.
Думаю она будет необходима и другим.

31 марта 2015 г., 23:57 пользователь NikitaFeodonit <
notifications@github.com> написал:

> Синхронизировать данные и фото постоянно - при WiFi и GPRS.
> Можно сделать настройку - синхронизировать фото только когда есть Wifi. Но
> она должна быть включена по умолчанию.
> 
> Что я понял.
> 
> Должна быть настройка "Синхронизировать фото только через WiFi", которая
> должна быть в_Ы_ключена (отключена) по-умолчанию. Если она включена, то
> через GPRS фото не должны синхронизироваться.
> 
> Всё остальное должно синхронизироваться при наличии любого вида связи.
> 
> Верно?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/13#issuecomment-88242478
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
Размер фото сейчас получается 20-30 кб. Можем ли мы этим пренебречь при GPRS-синхронизации? То есть надо ли тогда эту опцию делать?

**Comment by BishopGIS** [comment]
Да, согласен. Там в библиотеке вроде не много исправлять. При синхронизации в методах что для данных, что для фото идет запрос наличия подключения к сети. Там же можно и другие проверки поставить. См. https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/map/NGWVectorLayer.java#L964 и
 https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/map/NGWVectorLayer.java#L665

**Comment by yellow-sky** [comment]
я думаю можно и пренебречь. если занимает много времени на реализацию -
предлагаю отложить и закрыть тикет как неактуальный.

1 апреля 2015 г., 0:41 пользователь NikitaFeodonit <notifications@github.com

> написал:
> 
> Размер фото сейчас получается 20-30 кб. Можем ли мы этим пренебречь при
> GPRS-синхронизации? То есть надо ли тогда эту опцию делать?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/13#issuecomment-88259255
> .

## 

Best regards,

Nikulin Eugeny
