### ISSUE TITLE
Ошибка при открытии карты

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#131]
У Сергея на девайся воспроизводится стабильно
Попросил установить тестовую сборку.
Ждем репортов.

**Comment by yellow-sky** [comment]
Дополнение:

Если после установки программы местоположение еще ни разу не было определено (например, установку производили в помещении), то при попытке открыть карту из формы фиксации координат, приложение аварийно завершает свою работу.

**Comment by NikitaFeodonit** [comment]
При попытке открыть карту из формы ввода данных приложение аварийно завершает свою работу.
