### ISSUE TITLE
Останавливается синхронизация

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#132]
Тесткейс:
1) Запускаем приложение, добавляем новые объекты и тд.
2) Сворачиваем приложение
3) Выключаем GPS

Результат: приложение свернуто, но синхронизация не идет.
Должно быть: приложение свернуто, синхронизация продолжается

Заметка:
при открытии приложения весит окно с формой - Включите GPS. Может оно блокирует все?

**Comment by NikitaFeodonit** [comment]
Пока закрываем.
