### ISSUE TITLE
У фотографии отображается только рамка

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#136]
Скриншот:
![screenshot_2015-07-03-11-22-51](https://cloud.githubusercontent.com/assets/1277422/8499377/c41c21c4-219a-11e5-9c8e-2bfdd08181c0.png)

**Comment by yellow-sky** [comment]
Не подтвеждаю. У меня все ок.

**Comment by NikitaFeodonit** [comment]
Также такого у себя не замечал

**Comment by yellow-sky** [comment]
Проявилось на другом телефоне. Возможно ошибка из-за разрешения - 800х480

**Comment by yellow-sky** [comment]
До сих пор актуально. Есть подозрение, что нужно пробовать на фоне с маленьким экраном и маленькой памятью.

**Comment by NikitaFeodonit** [comment]
Один раз поймал у себя, в логах ничего особенного не увидел. Похоже, после закрытия окна фотокамеры и при возврате в окно нашего приложения происходит какая-то задержка, из-за которой не отрисовываются картинки.

**Comment by NikitaFeodonit** [comment]
На заметку, может пригодится. Из документации для BitmapFactory.decodeStream():
Prior to KITKAT, if is.markSupported() returns true, is.mark(1024) would be called. As of KITKAT, this is no longer the case.

Но на моем аппарате именно KitKat, поэтому это не должно влиять.

**Comment by NikitaFeodonit** [comment]
Но на моем аппарате именно KitKat, поэтому это не должно влиять.

**Comment by NikitaFeodonit** [comment]
Пока попробовал заменить AsyncTask на FutureTask. Понаблюдаем.

**Comment by yellow-sky** [comment]
Нужно заслать новую версию?

2015-08-17 21:49 GMT+03:00 NikitaFeodonit notifications@github.com:

> Пока попробовал заменить AsyncTask на FutureTask. Понаблюдаем.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/136#issuecomment-131924730
> .

## 

Best regards,

Nikulin Eugeny

**Comment by yellow-sky** [comment]
Выполнил создание объекта с фотографиями (появилось какое-то сообщение об ошибке, которое через некоторое время скрылось). Выполнил синхронизацию. Синхронизация была в 16:43. Пользователь: test

**Comment by NikitaFeodonit** [comment]
Исправлено.
