### ISSUE TITLE
Добавить прогресс-бар или другой контрол, показывающий, что идет процесс синхронизации.

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#137]
![image](https://cloud.githubusercontent.com/assets/1277422/8522580/281144ca-23f8-11e5-89b8-038a94d56e4b.png)

**Comment by yellow-sky** [comment]
Лучше показывать прогресс бар, который показывает сколько линий еще нужно синхронизировать.

**Comment by NikitaFeodonit** [comment]
Прогресс бар или что-либо другое на форме показать нет технической возможности.

Можно только на значке с круговыми стрелками в статус баре телефона, который появляется вначале синхронизации,  можно добавить число, отображающее что-либо, например, проценты.

**Comment by NikitaFeodonit** [comment]
> Прогресс бар или что-либо другое на форме показать нет технической возможности.

Мысль появилась, как это сделать, попробую.
