### ISSUE TITLE
Сделать замену в строчке с адресе линии

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#138]
Не умещаются наименования муниципальных районов/городских округов. Предлагаю вместо слова «область» выводить «обл.», вместо «городской округ» - «г.о.», вместо «муниципальный район» - «м.р.»
![image](https://cloud.githubusercontent.com/assets/1277422/8522602/65411adc-23f8-11e5-9880-988fe3c843cd.png)

**Comment by NikitaFeodonit** [comment]
Тут берутся значения с сервера, со списка слоев пользователя.
