### ISSUE TITLE
Галерея работает "странно"

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#14]
Если фото всего два, они странно смещены и могут быть сдвинуты за край экрана.
Если больше, то за край экрана может уходить больше фото, а на экране появляться пустое место.

**Comment by NikitaFeodonit** [comment]
Повторяется ли эта проблема при теперешней галерее?

**Comment by yellow-sky** [comment]
выложи в тест фери новую версию для проверки, плиз.

2015-03-04 21:39 GMT+03:00 NikitaFeodonit notifications@github.com:

> Повторяется ли эта проблема при теперешней галерее?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/14#issuecomment-77217877
> .

## 

Best regards,

Nikulin Eugeny

**Comment by yellow-sky** [comment]
Fixed
