### ISSUE TITLE
Placeholder в контролах ввода

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#144]
Цвет шрифта у надписей «Укажите способ прокладки» и «Введите комментарий» сделать одинаковым и изменить на серый. Введенные пользователем в эти поля данные отображать черным цветом.
![image](https://cloud.githubusercontent.com/assets/1277422/8522745/8e9a9272-23f9-11e5-8618-5e3149bf4aa8.png)

**Comment by NikitaFeodonit** [comment]
> Цвет шрифта у надписей «Укажите способ прокладки» ... сделать ... серый. Введенные пользователем в эти поля данные отображать черным цветом.

Для комбобокса это технически не возможно. Цвет надписи "Укажите способ прокладки" и цвет выбранного пользователем значения могут быть только одинаковыми, или серым, или черным. Пока оставил черный, чтобы для пользователя выбранное значение было лучше видно на солнце.

**Comment by NikitaFeodonit** [comment]
> Для комбобокса это технически не возможно

Оказался неправ. Возможно.
