### ISSUE TITLE
Возможность просмотра фото в галерее

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#15]
Для возможности оценить сделанное фото необходима возможность просмотра фото в полный экран.
Так же необходима возможность удаления фото из ранее сделанных.

**Comment by BishopGIS** [comment]
Может показывать через стандартную галерею (кажется так проще, через contentprovider), а то мы уже начинаем переписывать встроенный в андроид софт?
Удаление наверное это отдельный тикет?

**Comment by NikitaFeodonit** [comment]
При просмотре в полный экран должна показываться фотография из базы слоев, то есть та, что уйдет на сервер, чтобы (из #12)

> при просмотре из галереи будет видно какая фотка уйдет на самом деле
