### ISSUE TITLE
Убрать лишний запрос

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#155]
При фиксации координат первой точки появляется сообщение «Вы действительно хотите изменить статус линии?». Данное сообщение выводить не нужно.
![image](https://cloud.githubusercontent.com/assets/1277422/8522963/49dc3ef4-23fb-11e5-9181-7de4a5e81fe4.png)

**Comment by yellow-sky** [comment]
В сегодняшней сборки изменилось поведение.
 Каждый раз при фиксации координат после нажатия кнопки Готово появляется сообщение «Вы действительно хотите изменить статус линии?». Данное сообщение выводить не нужно.

**Comment by NikitaFeodonit** [comment]
В связи с закрытием #168 отпала необходимость в этом тикете, закрываю.
