### ISSUE TITLE
На первом экране поджать верхнюю часть

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#16]
На первом экране (выбор работ), необходимо поджать верхнюю часть экрана (отображение координат).
Все параметры необходимо разместить в одну строку (широта, долгота, точность), как в требованиях к мобильному приложению v2.
Так же предлагается рассмотреть вариант убрать панель - Координаты определены или не определены (она по факту не нужна).

Основная цель - сократить занимаемое место, чтобы экран был без прокрутки для большинства устройств. Возможно имеет смысл так же немного изменить размер кнопок, что бы они все помещались на экран.

**Comment by NikitaFeodonit** [comment]
> Все параметры необходимо разместить в одну строку (широта, долгота, точность), как в требованиях к мобильному приложению v2.

![device-2015-01-30-083036](https://cloud.githubusercontent.com/assets/8268336/5972474/6e9ed354-a85a-11e4-8930-a4fc11ceaac1.png)

На снимке экрана (3.3" 240x320) видно, что данные широты и долготы занимают всю строку. Это при малом размере шрифта. Уместить в этой же строке высоту и точность можно только за счет очень малого размера шрифта, который будет не читаться пользователем.

В случае сохранения размера шрифта придется удалить надписи "Шир", "Долг" и прочие. Получится примерно такой вариант:

![device-2015-01-30-090218](https://cloud.githubusercontent.com/assets/8268336/5972747/c23c583e-a85e-11e4-89fd-865b1f17e8ab.png)

где в верхней строке: широта долгота высота точность (количество цифр в значениях может быть реально у клиента, как понимаю). То есть даже не поместится в одну строку.

> Так же предлагается рассмотреть вариант убрать панель

"Рассмотреть" и "убрать" не есть одно и то же. Мне убрать не сложно, если дадите указание. Факт неопределенных координат понятен по факту отсутствия показания этих координат.

> Возможно имеет смысл так же немного изменить размер кнопок, что бы они все помещались на экран.

В случае с приведенным снимком экрана с эмулятора придется довольно сильно поджимать. Тут нужно определить, под какую диагональ и плотность точек экрана (или разрешение) выполнить изменение. Мои соображения об отношении диагонали к плотности точек я писал ранее [ссылка](https://github.com/nextgis/ngm_clink_monitoring/issues/1#issuecomment-71531401).

**Comment by BishopGIS** [comment]
Можно сами координаты выводить только в градусах, а не как сейчас ГМС итого будет 5 символов.

**Comment by yellow-sky** [comment]
Предлагаю выводить в десятичных и без подписей.
Панель убираем.
Кнопки пока оставляем как есть.

**Comment by NikitaFeodonit** [comment]
> итого будет 5 символов.

Это смотря какая будет точность после запятой. При слишком маленькой клиент может не увидеть изменения показаний координат при перемещении.

> Предлагаю выводить в десятичных и без подписей.

Если без подписей, то нужно обозначить южные широты и западные долготы через знак "-".

-158,12345678  -- это максимальное количество символов показаний без ограничений после запятой. Сколько оставлять будем?

**Comment by yellow-sky** [comment]
4ре символа после запятой

30 января 2015 г., 11:22 пользователь NikitaFeodonit <
notifications@github.com> написал:

> итого будет 5 символов.
> 
> Это смотря какая будет точность после запятой. При слишком маленькой
> клиент может не увидеть изменения показаний координат при перемещении.
> 
> Предлагаю выводить в десятичных и без подписей.
> 
> Если без подписей, то нужно обозначить какие-то полушария через знак "-".
> По моему, южные широты и западные долготы.
> 
> -158,12345678 -- это максимальное количество символов показаний без
> ограничений после запятой. Сколько оставлять будем?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/16#issuecomment-72168377
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
> 4ре символа после запятой

Для широты это будет изменение в 110 м, для долготы в 6 м (на широте в 58 гр).

**Comment by NikitaFeodonit** [comment]
На широте 0 гр -- те же 110 м

**Comment by NikitaFeodonit** [comment]
![device-2015-01-30-095932](https://cloud.githubusercontent.com/assets/8268336/5973285/bcf78436-a866-11e4-94db-10e5c1e961c1.png)

Можно и по 5 после запятой и на 10-тысячники подниматься. Еще место осталось.

**Comment by yellow-sky** [comment]
Давай лучше высоту уберем совсем и добавим СШ ВД

2015-01-30 12:01 GMT+03:00 NikitaFeodonit notifications@github.com:

> [image: device-2015-01-30-095932]
> https://cloud.githubusercontent.com/assets/8268336/5973285/bcf78436-a866-11e4-94db-10e5c1e961c1.png
> 
> Можно и по 5 после запятой и на 10-тысячники подниматься. Еще место
> осталось.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/16#issuecomment-72172204
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
Но высота есть в требованиях.

**Comment by NikitaFeodonit** [comment]
Вот пару вариантов с высотой и СШ/ВД. В обоих обозначения метров без пробела. В первом для координат 5 знаков, но без пробела перед СШ/ВД. Во втором 4 знака и с пробелом.

![device-2015-01-30-101117](https://cloud.githubusercontent.com/assets/8268336/5973436/7869e564-a868-11e4-823a-f8bcaf706286.png)

![device-2015-01-30-101200](https://cloud.githubusercontent.com/assets/8268336/5973437/786abd04-a868-11e4-8abe-4972b9977bc8.png)

**Comment by NikitaFeodonit** [comment]
Больше уже не войдет.

**Comment by yellow-sky** [comment]
Берем второй

**Comment by NikitaFeodonit** [comment]
Пока только изменил строку с показаниями, панель статуса еще не убирал, потому не закрыл issue.
