### ISSUE TITLE
Произвольно меняется линия

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#162]
Периодически самопроизвольно изменяется выбранная линия связи. Понять закономерность когда это происходит пока не удалось. У меня это случалось при следующих условиях: свернул приложение, погасил экран телефона, через некоторое время включил телефон и вызвал приложение. После этого заметил, что линия изменилась. Была «Мичуринский проспект», а изменилась на «г.Королев».

**Comment by yellow-sky** [comment]
Я думаю что в бэкграунде происходит синхронизация, и форма как то обновляется.

**Comment by NikitaFeodonit** [comment]
Скорее всего проблема та же, что и #163.

**Comment by NikitaFeodonit** [comment]
Закрыл #163. Понаблюдаем за этим.

**Comment by NikitaFeodonit** [comment]
Пока не повторяется, закрываю.
