### ISSUE TITLE
Синхронизация не останавливается, когда приложение выгружено из памяти.

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#164]
Период синхронизации = 1 час. 
Приложение выгружено из памяти, но через час синхронизация опять запускается. 
Скриншот:
![screenshot_2015-07-09-09-23-47](https://cloud.githubusercontent.com/assets/1277422/8594532/445361c8-264a-11e5-903d-5d2c2d3701ac.png)

**Comment by NikitaFeodonit** [comment]
Думаю, синхронизация была запущена, после чего по какой-то причине процесс синхронизации упал. Тогда возможна такая ситуация. Самого процесса уже нет в памяти, он упал, но в системе остался выставленным флаг об этом. Это окно как раз и показывает установленный этот флаг.

Сейчас в последних коммитах сделал сброс всякой синхронизации при старте приложения. В итоге зависший флаг работе мешать не должен. То есть приложение нужно выгрузить из памяти и запустить заново.

**Comment by NikitaFeodonit** [comment]
Если будет повторяться, откроем заново. Пока закрываю.
