### ISSUE TITLE
Сделать запись EXIF-данных сразу в маленький файл фото. Если нужно сохранить оригинальный, то копировать из маленького.

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/ngm_clink_monitoring#165]

**Comment by NikitaFeodonit** [comment]
Для ускорения обработки фотографий.

**Comment by yellow-sky** [comment]
Да, очень хороший кейс

2015-07-10 21:51 GMT+03:00 NikitaFeodonit notifications@github.com:

> Для ускорения обработки фотографий.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/165#issuecomment-120493221
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
У меня на 10 фото по 1200-1300 кбайт дало уменьшение времени на 14%. Но оставил изменение.
