### ISSUE TITLE
Перенести изменение статуса

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/ngm_clink_monitoring#168]
Перенос из nextgisweb_compulink_#116.

Поле «Статус строительства» занимает слишком много места на форме, хотя по факту изменять статус будут один единственный раз в конце строительства (если вообще будут). Статус строительства «Идет строительство» у нас устанавливается автоматически, а статус «Построено» мне кажется должен устанавливать руководитель проекта по результатам выездной проверки. Поэтому предлагаю поле «Статус строительства» убрать с формы, но возможность изменения статуса из мобильного приложения оставить. Для этого добавить в меню пункт «Изменить статус линии связи». Этот пункт меню должен быть доступен только с формы выбора Вида работ.
По кнопке открывается диалог выбора статуса, проекта (радио баттоны) и две кнопки - Ок, Отмена.

**Comment by NikitaFeodonit** [comment]
При выборе статуса Построено надо ли выводить дополнительный диалог-подтверждение?

**Comment by yellow-sky** [comment]
Нет
14.07.2015 19:03 пользователь "NikitaFeodonit" notifications@github.com
написал:
