### ISSUE TITLE
Странности с фото

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/ngm_clink_monitoring#169]
Перенос из nextgisweb_compulink_#118.

1) На вкладке Файлы у одной из точек прокладки кабеля отображается какая-то левая фотография, которую я снимал не вчера в полях, а накануне вечером в электричке, когда данные по Владимирской области еще не были загружены на сервер. Почему она отображается на карточке этого объекта?
![image](https://cloud.githubusercontent.com/assets/1277422/8624459/b19e0cf0-2740-11e5-8fc2-b66e70499ebd.png)
2) У одной из точек на сервере не отображаются фотографии, хотя я их точно делал. На фотографиях должно быть изображена яма, в которую уложены запасы кабеля (это место установки муфты). Когда я фиксировал эту точку у меня мобильное приложение несколько раз аварийно завершало работу.
![image](https://cloud.githubusercontent.com/assets/1277422/8624471/c2a2725c-2740-11e5-8c91-2cdc6f655b97.png)

Я попросил копию дирректории с его мобильного, может поможет:
https://drive.google.com/open?id=0B8fD-l_uK4vFNGxjZDAxci1CeDVmX0tONjlHR2ZTeUtzT21N

**Comment by NikitaFeodonit** [comment]
> 2) У одной из точек на сервере не отображаются фотографии, хотя я их точно делал. На фотографиях должно быть изображена яма, в которую уложены запасы кабеля (это место установки муфты). Когда я фиксировал эту точку у меня мобильное приложение несколько раз аварийно завершало работу.

Эта точка есть. Получились две точки с почти равными координатами:

id 9 -- https://gis.compulink.ru/resource/8192/feature/9
id 10 -- https://gis.compulink.ru/resource/8192/feature/10

У 9-й нет фотографий. У 10-й есть как раз с ямой с кабелем.

Проблема оказалась в том, что на карте они накладываются друг на друга, а сверху оказывается 9-я, без фотографий. А возможности увеличить карту так, чтобы они разделились, нет.

Вот их координаты в метрах:
9-я
4538059.239853258, 7608712.768284127

10-я
4538059.254102154, 7608712.741032529

То есть разница получилась по обеим осям координат в 2.5 см.

**Comment by NikitaFeodonit** [comment]
Пока для заметки по 1-му пункту. Объект этот:
https://gis.compulink.ru/resource/8192/feature/1

Путь в базе приложения:
com.nextgis.ngm_clink_monitoring\files\map\layer_20150703111934136\layer_201507090850584780\layer_20150709085108535\1\

**Comment by NikitaFeodonit** [comment]
> 1) ... Почему она отображается на карточке этого объекта?

Скорее всего произошло следующее.

Вечером была сделана фотография, был записан временный файл фотографии в рабочей папке программы.

Но при дальнейших действиях приложение аварийно завершило работу. В итоге временный файл остался не обработанным и не удаленным.

При создании нового объекта были созданы новые фотографии, временные файлы которых были обработаны вместе с вечерним предыдущим. Это подтверждается записанными в базу на сервере именами файлов, в которых содержится дата съемки:
Optical_Cable_Laying_20150708_210144.jpg
Optical_Cable_Laying_20150709_124127.jpg
Optical_Cable_Laying_20150709_124136.jpg

Временные файлы фотографий не удаляются специально, чтобы не повторять пересъемку объекта в случае аварийного завершения приложения.

И эта вечерняя фотография должна была отображаться при создании нового объекта еще до съемки новых фотографий, а также вместе с новыми после съемки новых фотографий. Но это могло остаться не замеченным.

**Comment by NikitaFeodonit** [comment]
Пока не закрываю до отзывов клиента.

**Comment by yellow-sky** [comment]
Не воспроизводится в текущий момент
