### ISSUE TITLE
Закрытие формы ввода очень длительное

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/ngm_clink_monitoring#174]
Очень долго закрывается форма ввода данных после нажатия кнопки Готово. Форма закрывается 5-10 сек.

**Comment by NikitaFeodonit** [comment]
Раза в два смог сократить. Понаблюдаем еще.

**Comment by NikitaFeodonit** [comment]
Проверил в эмуляторе -- при ~50 слоях закрытие первый раз около 7 сек, последующие 4 сек. На реальном аппрате должно быть быстрее.

**Comment by NikitaFeodonit** [comment]
Все измерения делал при ~50 линиях связи.

Если синхронизация не выполнялась, то закрытие формы создания объекта происходит довольно быстро, на моем аппарате в пределах 2-3 сек.

Если закончилась сихронизация при открытой форме создания, то происходит перезагрузка всей карты со всеми слоями. После окончания загрузки карты происходит перерисовка формы создания.

В итоге иной раз увеличивается время вставки в базу (вместо 400 мс может быть до 3000 мс), приэтом закрытие формы может быть до 8 сек.

Но даже если вставка в базу в пределах 400-600 мс, закрытие формы немного увеличивается, вместо 2-3 сек может быть 3-4 сек.

**Comment by NikitaFeodonit** [comment]
Все измерения делал при ~50 линиях связи.

**Comment by BishopGIS** [comment]
Может вставку в БД вынести в отдельный поток, независимо от формы?

**Comment by NikitaFeodonit** [comment]
Перевел работу с базой в отдельный поток, а для пользователя показываю диалог ожидания.
