### ISSUE TITLE
Отключить сообщения об отправке отчета

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#177]
Тоже не нужно. Эта информация только для нас нужна.
Отправка в автоматическом режиме тоже не должна показывать эти сообщения.

**Comment by NikitaFeodonit** [comment]
Надо ли выводить сообщения, если пользователь отправил базу разработчикам из меню?

**Comment by yellow-sky** [comment]
Сообщения об отчете нет.
Сообщения об отправки данных тут -  https://github.com/nextgis/ngm_clink_monitoring/issues/178
