### ISSUE TITLE
Заблокировать возможность создания более одного NGW-подключения

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/ngm_clink_monitoring#18]
Уже сейчас код работает только с первым подключением в списке.

**Comment by simgislab** [comment]
а почему?

**Comment by NikitaFeodonit** [comment]
По описанию приложения не увидел возможности и необходимости работать с несколькими подключениями.

**Comment by simgislab** [comment]
а сорри, компьюлинк! я про NGM подумал

**Comment by BishopGIS** [comment]
Там я только пример дал кода с работой первого подключения. Если нет ни одного подключения приложение упадет. Там это надо делать более логичным, с проверками и чтением подключения из настроек.

**Comment by NikitaFeodonit** [comment]
Тот пример я уже немного переделал и добавил нужные проверки, если нет ни одного подключения.

**Comment by NikitaFeodonit** [comment]
Сейчас из всего списка подключений выбирается только первое.

**Comment by BishopGIS** [comment]
Я имел  в виду, что подключение уникально идентифицируется по имени и поэтому первое брать не стоит, а брать надо, то что ты записал в свойства программы при создании аккаунта через кастомный диалог. Например, что то типа

``` java
 String accountName = preferences.grtString(KEY_CL_ACCOUNT)
```

Ведь нет гарантии, что у пользователя не стоит еще программ с нашими аккаунтами и будет выбираться НГВ который и не поддерживает компьюлинковский функционал.

**Comment by NikitaFeodonit** [comment]
> брать надо, то что ты записал в свойства программы при создании аккаунта через кастомный диалог

Да, можно так отфильтровать подключения для Complulink Monitoring. Но если у пользователя стоят программы Complulink Monitoring и NextGIS Mobile, то мобильное может запустить синхронизацию и для подключений Complulink Monitoring. Поэтому я думаю, что нужно разделить подключения по типу, чтобы для каждой программы был свой набор подключений.

**Comment by BishopGIS** [comment]
Для разделения по типу, тебе придется забрать часть библиотеки себе. Там не все можно программно выставить (тип). Например, в некоторых местах тип подключения пишется в xml: например в authenticator.xml. Не уверен что это хорошая идея будет, тебе придется фиксить баги, которые мы будет в библиотеке исправлять или как-то синхронизировать исходники.
