### ISSUE TITLE
Залить данные из присланных архивов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#181]
Необходимо просмотреть данные которые не синхронизировались и либо вручную, либо автоматом синхронизировать их.
Структура слоев уже отличается (DATE - DATETIME), необходимо об этом помнить.
Фото так же должны быть приатачены.

**Comment by yellow-sky** [comment]
https://gis.compulink.ru/mobile_debug/message/38
https://gis.compulink.ru/mobile_debug/message/5

**Comment by NikitaFeodonit** [comment]
Залил.
