### ISSUE TITLE
Есть ли возможность запускать обновление из самой программы

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#183]
Необходимо выяснить, можно ли запустить обновление программы из гугл плей, непосредственно из пункта меню самой программы.
Либо вызывать окно гугл плей с открытой страницей нашего приложения.

**Comment by NikitaFeodonit** [comment]
Официального API нет, поэтому сделал только открытие по ссылке страницы нашего приложения.

**Comment by yellow-sky** [comment]
Ok

18 августа 2015 г., 13:35 пользователь NikitaFeodonit <
notifications@github.com> написал:

> Официального API нет, поэтому сделал только открытие по ссылке страницы
> нашего приложения.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/183#issuecomment-132161568
> .

## 

Best regards,

Nikulin Eugeny
