### ISSUE TITLE
Разделить подключения Compulink Monitoring и NextGIS Mobile

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/ngm_clink_monitoring#19]
Если у пользователя установлены обе программы, то каждая из них может пытаться управлять синхронизацией и прочим для списка подключений.

**Comment by NikitaFeodonit** [comment]
Думаю, нужно через создание и использование константы, подобной
com.nextgis.maplib.util.Constants.NGW_ACCOUNT_TYPE

**Comment by BishopGIS** [comment]
Эта константа "зашита" в библиотеку. Тебе иначе придется весь код связанный с этим себе переносить. Проще через интерфейс программы ограничить показ только необходимых подключений, например, записав в настройки название аккаунта. А за системный интерфейс мы не отвечаем.

**Comment by NikitaFeodonit** [comment]
Развязал через переменные gradle. Пока только не смог сделать замену для иконок в файле

**Comment by NikitaFeodonit** [comment]
Развязал через переменные gradle. Пока только не смог сделать замену для иконок в файле
maplibui/res/xml/authenticator.xml
Через resValue можно только string, не drawable, а программно менять иконки с использованием buildConfigField нет возможности. Иконки можно прописать только в authenticator.xml.

Остается вариант или через замену строковых вхождений в xml файлах средствами gradle в момент компиляции, но пока не получил работающего решения.

Или описание сервиса NGWAuthenticatorService, в котором используется файл authenticator.xml, перенести из библиотечного манифеста в основной в модуле app.

**Comment by NikitaFeodonit** [comment]
> Или описание сервиса NGWAuthenticatorService, в котором используется файл authenticator.xml, перенести из библиотечного манифеста в основной в модуле app.

Конечно, вместе с переносом файла authenticator.xml в ресурсы app.

**Comment by NikitaFeodonit** [comment]
Разобрался в ненужности данного разделения. Изменения откатил, закрываю.
