### ISSUE TITLE
Отображение местоположения пользователя на карте

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#2]
При переключении на вкладку Карта, должна быть кнопка спозиционировать карту по месторасположению пользователю (setZoomAtCentre).
Так же должен быть слой-оверлей, который отображает местоположение пользователя - буква X (черно-синяя, как логотип NextGIS) в белом кружочке. Дима говорит, что это лучше сразу реализовать в android_maplibui.

**Comment by BishopGIS** [comment]
По первой части тикета: https://github.com/nextgis/android_gisapp/blob/master/app/src/main/java/com/nextgis/mobile/MainActivity.java#L183

**Comment by yellow-sky** [comment]
Необходимо не только центрировать карту, но и приближаться на 16 уровень
