### ISSUE TITLE
Добавить предупреждение при удалении подключения

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/ngm_clink_monitoring#20]
С примерно таким текстом "Все данные по проекту ВОЛС будут удалены! Продожить?". Так как при удалении подключения удаляются все слои. Возможно вместе с не отправленными на сервер изменениями.

**Comment by yellow-sky** [comment]
Да, я думаю стоит.

**Comment by NikitaFeodonit** [comment]
Добавил через [коммиты в maplibui](https://github.com/nextgis/android_maplibui/commit/d743233d65d6b1d953b000a5cba8985822b3fde0).
