### ISSUE TITLE
Рефакторинг формы ввода статуса

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#21]
Необходимо переделать форму ввода статуса объекта, разбив её на два экрана.

На первом экране должны отображаться контрол выбора линии, и список объектов (тип в зависимости от выбора на первом экране, например Строительные длины) с проставленными статусами в правой части строки.
![screenshot_2015-01-25-11-56-18__](https://cloud.githubusercontent.com/assets/1277422/6146081/ef7551ee-b1f9-11e4-98b6-06026bf4c898.png)

После выбора конкретного объекта должна появляться вторая форма:
![screenshot_2015-01-25-11-56-18_2](https://cloud.githubusercontent.com/assets/1277422/6146085/fb629e6c-b1f9-11e4-90f8-74fc6561b6fb.png)
На этой форме указаны линия и название объекта, кнопки Построен\Не построен, а так же галерея фотографий заданного объекта. Кнопку необходимо сделать такой, чтобы было понятно в каком сейчас состоянии объект.

**Comment by NikitaFeodonit** [comment]
Пользователь может менять статус объекта в обе стороны (Не построен -> Построен, Построен -> Не построен) или только в одну сторону (Не построен -> Построен)?

**Comment by NikitaFeodonit** [comment]
Пожалуй, в обе. Если случайно нажал не то, то чтоб мог исправить.

**Comment by NikitaFeodonit** [comment]
> Пожалуй, в обе. Если случайно нажал не то, то чтоб мог исправить.

Только в этом случае для объекта всё равно пропишется дата изменения статуса.

**Comment by yellow-sky** [comment]
Это нормально
12.02.2015 12:57 пользователь "NikitaFeodonit" notifications@github.com
написал:
