### ISSUE TITLE
Если установлено NextGIS Mobile, то падает release-сборка при попытке залогиниться при создании подключения.

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/ngm_clink_monitoring#23]
Вылетает с ошибкой

**Comment by NikitaFeodonit** [comment]
Вылетает с ошибкой
java.lang.SecurityException: caller uid 10098 is different than the authenticator's uid

Разные методы решения описаны по [ссылке](http://stackoverflow.com/questions/3774282/securityexception-caller-uid-xxxx-is-different-than-the-authenticators-uid), но у нас, как будто, всё сделано правильно.

Проблема именно сочетания двух программ. Причем у меня NextGIS Mobile debug-сборка, а Compulink Monitoring release-сборка.

**Comment by BishopGIS** [comment]
Я же проверял. У меня не воспроизводится. Может чего внесли нового в код. Я проверю еще раз.

**Comment by NikitaFeodonit** [comment]
У меня в прошлый раз, когда уже была деинсталирована NextGIS Mobile, была проблема с этой ошибкой. Решилось добавлением USE_CREDENTIALS разрешения в манифесте. Но это было при отсутствии NextGIS Mobile. Сейчас выплыло на этом сочетании вместе установленных двух программ.

**Comment by BishopGIS** [comment]
Проверили еще раз.
Если обе проги собраны под отладкой (debug) все ок.
Если compulink под release, а gisapp под debug падает.
Нужно проверить, что бы обе были подписаны.

**Comment by NikitaFeodonit** [comment]
Проверил обе подписанные release сборки. Падает.

Сначала поставил NextGIS Mobile, в нем создал подключение и загрузил слой.

Потом поставил наше приложение. При попытке входа при создании подключения падает с ошибкой
java.lang.SecurityException: caller uid 10209 is different than the authenticator's uid
то есть ситуация та же.

**Comment by NikitaFeodonit** [comment]
> Если compulink под release, а gisapp под debug падает.

В обратной ситуации также падает, то есть compulink под debug, а gisapp под release.

Так хоть можно отладить попытаться.

**Comment by NikitaFeodonit** [comment]
В качестве размышления -- может быть всё дело в сертификате? Может для данной ситуации должен быть сертификат с какими-то другими свойствами?

Я сертификатов не создавал, потому не знаю, какие у них могут быть особенности. Потому это только предположение.

**Comment by BishopGIS** [comment]
Косяков много где может быть. 
1. Я поменял контекст для получения AccountManager
2. Есть конкретная инструкция для отладки http://stackoverflow.com/a/6072364
3. Возможно описание сервиса NGWAuthenticatorService надо перенести из манифеста библиотеки в манифест программы

Линки
https://bugzilla.mozilla.org/show_bug.cgi?id=716798
http://stackoverflow.com/questions/10300534/securityexception-when-trying-to-add-an-account
http://stackoverflow.com/questions/3774282/securityexception-caller-uid-xxxx-is-different-than-the-authenticators-uid

**Comment by NikitaFeodonit** [comment]
Исправил через [коммит](https://github.com/nextgis/android_gisapp/commit/dc5dd88b82d2d4732c59f8ef0b151e89c090dbd7) в NextGIS Mobile.

> У меня в прошлый раз, когда уже была деинсталирована NextGIS Mobile, была проблема с этой ошибкой. Решилось добавлением USE_CREDENTIALS разрешения в манифесте. Но это было при отсутствии NextGIS Mobile.

В Compulink Monitoring я тогда добавил это разрешение, а в NextGIS Mobile нет. Теперь добавил его и там. Всё работает.

Но **обе сборки должны быть release** или debug. Иначе не работает.

**Comment by NikitaFeodonit** [comment]
> Я поменял контекст для получения AccountManager

Я в мобильном еще пару моментов для него исправил, но это не помогло. Только после добавления разрешения USE_CREDENTIALS в манифесте всё заработало.

**Comment by NikitaFeodonit** [comment]
Если одно или оба приложения установлены через сервер testfairy.com, то не работает.

**Comment by BishopGIS** [comment]
Значит для феи надо отключать. Было бы неплохо в вики к android-gisapp
отразить эту особенность. Чтобы потом не искать концы. Сможешь коротенько
описать что за credetials?

**Comment by NikitaFeodonit** [comment]
> Значит для феи надо отключать.

Кого отключать? Разрешение? Так без него вообще не работает при двух программах. Точнее, работает только, если обе сборки debug.

**Comment by NikitaFeodonit** [comment]
Для тестового сервера решения пока не искал. Для него, похоже, нужно одно из приложений удалять полностью.

**Comment by NikitaFeodonit** [comment]
> Сможешь коротенько описать что за credetials?

Хорошо.

**Comment by NikitaFeodonit** [comment]
Открыл, чтобы не забыть за вики.

**Comment by NikitaFeodonit** [comment]
Вики сделал, тут закрываю.
