### ISSUE TITLE
Добавление аккаунта при первой входе в программу

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#24]
Почему при первом запуске приложения заблокированы кнопки выбора вида работ? Предполагаю что это связано с тем, что еще не произошла синхронизация данных, т.к. пока не создана учетная запись.  
Если и это так, то при первом запуске приложения нужно сразу открывать диалог ввода учетных данных (логин и пароль).

**Comment by NikitaFeodonit** [comment]
> Почему при первом запуске приложения заблокированы кнопки выбора вида работ?

Показывать нечего. Некий намек на необходимость загрузки данных.

> при первом запуске приложения нужно сразу открывать диалог ввода учетных данных (логин и пароль).

Хорошо.
