### ISSUE TITLE
Перенести кнопку 'Сделать Фото'

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#26]
Кнопка «Сделать фото» находится за пределами экрана. Чтобы ее увидеть нужно прокрутить экран вниз, что неочевидно. Предлагаю кнопку «Сделать фото» отображать над списком фотографий, а не под ним как сейчас. Помимо надписи предлагаю отображать на фото пиктограмму с изображением фотоаппарата.

**Comment by NikitaFeodonit** [comment]
> отображать на фото

... или на кнопке "Сделать фото"?

**Comment by yellow-sky** [comment]
На кнопке
13.02.2015 16:10 пользователь "NikitaFeodonit" notifications@github.com
написал:
