### ISSUE TITLE
Изменить пиктограмму в списке объектов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#27]
Изменить пиктограмму, символизирующую, что данный объект построен. Предлагаю у построенных объектов отображать пиктограмму с изображением зеленой галочки, а у не построенных туже самую пиктограмму, но светло серого цвета.

**Comment by NikitaFeodonit** [comment]
Еще, как вариант, можно было бы использовать галочку чекбокса, как на снимке экрана. Только, конечно, разместить ее в списке с правой стороны. Стандартный элемент системы.

![checkbox-example](https://cloud.githubusercontent.com/assets/8268336/6399571/8f1aaf78-bdf3-11e4-8b0a-69b5ba831a2e.png)

**Comment by NikitaFeodonit** [comment]
Так как элемент стандартный, то его цветовое оформление будет зависеть от всего оформления приложения. То есть будет выглядеть в стиле всего приложения.

**Comment by yellow-sky** [comment]
Никита, давай я приложу этот скриншот к нашему предложению. Если
понравится, реализуемых его.
26.02.2015 22:21 пользователь "NikitaFeodonit" notifications@github.com
написал:

**Comment by NikitaFeodonit** [comment]
Выполнено через #38.
