### ISSUE TITLE
Выделение выпадающего списка Линий

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#29]
Сейчас форме списка объектов неочевидно, что можно выбрать другую ВОЛС. Поле больше похоже на надпись, чем на поле выбора. Нужно как-то выделить контрол выбора ВОЛС, чтобы было интуитивно понятно, что значение в этом поле можно поменять. Предлагаю по умолчанию выводить надпись «-- выберите ВОЛС --» вместо тог, чтобы подставлять первую ВОЛС в списке.

**Comment by NikitaFeodonit** [comment]
Когда сделаем автоматический выбор линии на основе местоположения пользователя, то тогда там уже должна быть выбрана конкретная ВОЛС. Тогда надписи «-- выберите ВОЛС --» видно не будет. Думаю, нужно как-то иначе выделить.

**Comment by yellow-sky** [comment]
Пока не реализовывать!

**Comment by yellow-sky** [comment]
Не актуально
