### ISSUE TITLE
Отображение объектов из загруженных слоев на карте

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#3]
При переключении на Карту, должны отображаться все типы слоев из всех ВОЛС, которые загружены на устройство:
-  Строительная длина ОК  
-  Оптическая муфта  
-  Оптический кросс  
-  Столб/Оконечная опора  
-  Телекоммуникационный шкаф

**Comment by NikitaFeodonit** [comment]
Сейчас, как я вижу, отображаются все объекты. Женя, можешь проверить у себя?

**Comment by yellow-sky** [comment]
Работает
