### ISSUE TITLE
Замена контрола статуса объектов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#30]
Стандартный контрол тоже не подойдет, но и в текущем варианте непонятно какая из двух кнопок нажата. Может быть чекбоксом заменить? Надпись у чекбокса будет «Построено».

**Comment by yellow-sky** [comment]
Предлагаю сделать скриншот формы в дизайнере и отослать на согласование.

**Comment by NikitaFeodonit** [comment]
Из #27:

> Предлагаю у построенных объектов отображать пиктограмму с изображением зеленой галочки, а у не построенных туже самую пиктограмму, но светло серого цвета.

Можно ту же галочку сделать для этого чекбокса. Только мне пока не понятно, как его выполнить. Как вариант, большое слово "Построен", а рядом эта галка. Когда не построен объект, то и слово, и галка серые. Когда построен -- слово черным, а галка зеленым. Примерно так:

# Построен ^

только галка наоборот, конечно.

**Comment by yellow-sky** [comment]
Давай попробуем так, если это не сильно усложнит

13 февраля 2015 г., 16:35 пользователь NikitaFeodonit <
notifications@github.com> написал:

> Из #27 https://github.com/nextgis/ngm_clink_monitoring/issues/27:
> 
> Предлагаю у построенных объектов отображать пиктограмму с изображением
> зеленой галочки, а у не построенных туже самую пиктограмму, но светло
> серого цвета.
> 
> Можно ту же галочку сделать для этого чекбокса. Только мне пока не
> понятно, как его выполнить. Как вариант, большое слово "Построен", а рядом
> эта галка. Когда не построен объект, то и слово, и галка серые. Когда
> построен -- слово черным, а галка зеленым. Примерно так:
> Построен ^
> 
> только галка наоборот, конечно.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/30#issuecomment-74253824
> .

## 

Best regards,

Nikulin Eugeny

**Comment by yellow-sky** [comment]
Новый вариант от заказчика:
Во всех формах ввода статуса объектов (включая измерение линии) необходимо заменить кнопки на RadioButton.

Статус работ: \* Выполнено   \* Не выполнено

Предлагаю сделать скриншот формы с черными надписями а так же с надписями зеленого и красного цветов.
