### ISSUE TITLE
Останавливать синхронизацию при выгрузке приложения из памяти

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#33]
Когда программа выгружается пользователем из памяти (слайд в меню свернутых приложений) синхронизация должна отключаться. При старте приложения, синхронизация должна включаться автоматически.
Когда приложение свернуто, синхронизация должна продолжаться!

**Comment by NikitaFeodonit** [comment]
Сейчас синхронизация стоит с периодом в 10 минут. За это время пользователь может сделать изменения и выгрузить приложение. Тогда синхронизация не запуститься и данные не уйдут на сервер.

Надо бы при очередной сихронизации проверять, отсутствуют ли изменения и выгружена ли программа. Если есть изменения, то их отправить и остановить автосинхронизацию, если программа выгружена.

**Comment by yellow-sky** [comment]
А мы можем при закрытии программы принудительно запустить разово синхронизацию и отключать автоматическую?

**Comment by NikitaFeodonit** [comment]
Как понимаю, технически невозможно выполнить, так как

> Когда программа выгружается пользователем из памяти (слайд в меню свернутых приложений)

в этот момент система не отдает приложению никаких событий, приложение просто уничтожается.

> Когда приложение свернуто

в этот момент уже все события активити прошли, по ним нельзя ориентироваться.

Остается только вариант не из приложения управлять, а из сервиса синхронизации. При очередной синхронизации проверять, есть ли приложение в памяти. Если нет, то выполнить синхронизацию и сбросить флаг автоматической синхронизации.

**Comment by BishopGIS** [comment]
Я уже предлагал вариант проще это сделать. Синхронизация запускается по таймеру. Умерло приложение - таймер остановился - синхронизация остановилась.

**Comment by NikitaFeodonit** [comment]
По таймеру синхронизация сейчас и так срабатывает, по системному. Какой таймер тогда ты имеешь ввиду?

**Comment by NikitaFeodonit** [comment]
И еще нужно выполнить синхронизацию в момент или после закрытия приложения на случай возможных изменений. В момент закрытия нет никаких сигналов от системы, то есть немозможно. Остается только через сервис синхронизации.

**Comment by BishopGIS** [comment]
Я имею в виду отключить системный таймер и запускать только по таймеру в приложении. Там есть такой способ запуска синхронизации - по событию. А если вдруг будет пропущена последняя синхронизация - ничего страшного в этом не вижу. Да и не определить это никак, т.к. ты сам пишешь, что приложения закрывается без каких-то предупреждений от системы. В общем пропуск одной синхронизации не страшен. Все равно при запуске сработает таймер и все синхронизируется.

Да, хочу напомнить как может запускаться синхронизация:
1. По событию в приложении (поменялись данные, сработал таймер и т.п.)
2. По системному таймеру
3. По событию от Google Service
4. При подключении девайса к сети (если до этого сети не было)
5. По команде пользователя

Вам нужен только вариант 1, ну и 5. Остальные надо отключить.

http://developer.android.com/training/sync-adapters/running-sync-adapter.html

**Comment by NikitaFeodonit** [comment]
Автоматическая синхронизация теперь управляется из приложения.

Синхронизация запускается при старте приложения, если есть учетная запись. Сделано в соответствии с "Требования к мобильному приложению ГИС v2.docx".
