### ISSUE TITLE
Принудительное включение GPS 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#34]
При старте программа должна проверять, что GPS включен.
Если не включен, должна попытаться включить его принудительно (если это вообще возможно! я не знаю) и выключить при выгрузке, если программа сама его включила.
Если включить нельзя, то при старте предлагать пользователю включить его и перекидывать в системные настройки, где включается этот флаг.

**Comment by NikitaFeodonit** [comment]
Принудительно заставлять включать определение координат по спутникам.
