### ISSUE TITLE
Изменить общий дизайн приложения

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#38]
Клиенту не нравится общее оформление приложения - по его мнению дизайн не целостный и изобилует нестандартными панелями и тд. Он согласился, что мы сделали все один-в-один с его макетами, но результат не очень хороший. Он отказывается от своего варианта и просит нас сделать предложения по дизайну.
Как вариант мы можем предложить изменить все формы в соответствии с парадигмой Material Design:
http://www.google.co.uk/design/
https://developer.android.com/design/index.html

В нашем случае, как мне кажется, мы должны удалить все разноцветные панельки с надписями, выбрать шрифт, выправить все размеры шрифтов у надписей, оформить списки в соответствии с этой парадигмой. Так же изменить вид кнопки (Сделать фото) и кнопок выбора работ в соответствии с этим дизайном.
Верхняя панель, насколько я понимаю и меню соответствует Material Design.
Возможно, переход между формами со спискам нужно сделать свайпом влево и вправо.

**Comment by NikitaFeodonit** [comment]
> Возможно, переход между формами со спискам нужно сделать свайпом влево и вправо. 

Думаю, это будет одним лишним движением больше. Сейчас нажал на элемент в списке -- открылась следующая форма. А так нужно нажать элемент для выбора, а потом еще сделать движение для смены форм.
