### ISSUE TITLE
Всплывающее окно при тапе по объекту

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#4]
При щелчке по объекту, на вкладке карта должно появляться окно с короткой информацией об объекте. (предлагается выводить все непустые поля)

**Comment by NikitaFeodonit** [comment]
Предполагается долгое нажатие по объекту или короткое?

**Comment by NikitaFeodonit** [comment]
Думаю, лучше длинное нажатие, чтобы предотвратить случайное нажатие по
 карте.

**Comment by yellow-sky** [comment]
Да
 16.04.2015 18:22 пользователь "NikitaFeodonit" notifications@github.com
написал:
