### ISSUE TITLE
Ориентация фото в галереи

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#42]
У заказчика проявляется странное поведение: как бы он не фоткал (вертикально или горизонтально, фото в галерее всегда горизонтальные 
![screenshot_2015-03-11-17-07-17](https://cloud.githubusercontent.com/assets/1277422/6598700/7eae8344-c816-11e4-9f8e-68ab273896d3.png)
У меня такое не проявляется. Может баг Sony Experia?

**Comment by NikitaFeodonit** [comment]
Наше приложение ничего для ориентации не делает. Просто берет то, что отдало системное приложение для фотографирования.

В моем аппарате при вертикальной съемке выдает разрешение 1456х2592, при горизонтальной -- 2592х1456, то есть наоборот. А приложение просто обрабатывает полученные файлы как есть.

**Comment by NikitaFeodonit** [comment]
> Может баг Sony Experia?

Скорее всего это не баг, а отсутствующая или не настроенная функция. Один из вариантов, что этот аппарат прописывает значение ориентации в EXIF, не меняя отношение сторон файла.

**Comment by NikitaFeodonit** [comment]
Пусть он мне пришлет пару фото, горизонтально и вертикально сфотографированных. Из папки
/sdcard/ngm_clink_monitoring
или
/mnt/ngm_clink_monitoring
Я посмотрю, что его аппарат прописывает в EXIF.

**Comment by yellow-sky** [comment]
ок

11 марта 2015 г., 21:22 пользователь NikitaFeodonit <
notifications@github.com> написал:

> Пусть он мне пришлет пару фото, горизонтально и вертикально
> сфотографированных. Из папки
> /sdcard/ngm_clink_monitoring
> или
> /mnt/ngm_clink_monitoring
> Я посмотрю, что его аппарат прописывает в EXIF.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/42#issuecomment-78337662
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
У клиента в EXIF прописывает тег ориентации, оставляя неизменным соотношение сторон.

Выполнил через решение issue #51.
