### ISSUE TITLE
Дизайн. Ужать кнопку для фото

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#46]
Кнопку для фото сделать поуже, чтобы она отличалась от простых панелей

**Comment by NikitaFeodonit** [comment]
Только сейчас возник вопрос -- уже по ширине или по высоте?

**Comment by NikitaFeodonit** [comment]
И правильно ли я понимаю, что речь идет о кнопке "Сделать фото"?

**Comment by yellow-sky** [comment]
Да, Сделать Фото.
Уже по ширине. Как на картинке, которую присылал заказчик.

11 марта 2015 г., 21:14 пользователь NikitaFeodonit <
notifications@github.com> написал:

> И правильно ли я понимаю, что речь идет о кнопке "Сделать фото"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/46#issuecomment-78333463
> .

## 

Best regards,

Nikulin Eugeny
