### ISSUE TITLE
Выложить версию в GooglePlay

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#48]
Необходимо выложить нынешнюю версию в GPlay. 
При этом:
1) Проверить все атрибуты нашей компании как разработчика (к Максиму)
2) Убрать пользователь\пароль из формы создания аккаунта
3) Вставить новый адрес сервера по умолчанию: https://gis.compulink.ru

**Comment by yellow-sky** [comment]
По 1):  
- Слово лицензия выделить болдом  
- Перед строчкой Copyright добавить еще одну строку:  
  Основано на _NextGIS Mobile_ (<-это ссылка http://nextgis.ru/nextgis-mobile/)

**Comment by NikitaFeodonit** [comment]
> Слово лицензия выделить болдом

У нас там слово "Лицензии:". Это для уточнения.

> Перед строчкой Copyright добавить еще одну строку: Основано на NextGIS Mobile

Так и сделать слова "NextGIS Mobile" курсивом?

**Comment by yellow-sky** [comment]
У нас там слово "Лицензии:" - да выделить всю эту строку

Так и сделать слова "NextGIS Mobile" курсивом? - нет, это я ссылку так
показал :) на гитхабе нельзя сделать ссылку по-человечески. Должно быть так:
Основано на NextGIS Mobile http://nextgis.ru/nextgis-mobile/

3 апреля 2015 г., 17:42 пользователь NikitaFeodonit <
notifications@github.com> написал:

> Слово лицензия выделить болдом
> 
> У нас там слово "Лицензии:". Это для уточнения.
> 
> Перед строчкой Copyright добавить еще одну строку: Основано на NextGIS
> Mobile
> 
> Так и сделать слова "NextGIS Mobile" курсивом?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/48#issuecomment-89307790
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
> на гитхабе нельзя сделать ссылку по-человечески. Должно быть так:

Посмотришь вживую в приложении, скажешь, правильно ли я понял.

**Comment by NikitaFeodonit** [comment]
Для приложения на GPlay надо бы придумать описание на русском и английском, как я понимаю.

**Comment by yellow-sky** [comment]
Нет, пусть сами придумывают. Не наша задача
03.04.2015 18:31 пользователь "NikitaFeodonit" notifications@github.com
написал:

**Comment by yellow-sky** [comment]
Задача переведена на заказчика
