### ISSUE TITLE
Запрет работы приложения без запущенного GPS

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#50]
Можно ли выходить из приложения, если после предложения запустить GPS, пользователь отказался от этого, и смартфон так и не имеет точного позиционирования.

**Comment by BishopGIS** [comment]
Это будет выглядеть как падение. Лучше деактивировать все кнопки и писать где нибудь, что необходимо активировать GPS для работы ПО.

**Comment by NikitaFeodonit** [comment]
Решая issue #34, я сделал так, что если пользователь отключил функции определения местоположения в системных настройках, то при появлении окна приложения появляется диалог с кнопкой ОК, по которой можно попасть только в эти настройки для включения GPS. Пока не включит, будет выдавать этот диалог.

Остается только проблема, если GPS включен, а координаты не определены. Тут блокировки я не делал. Сделать?

**Comment by yellow-sky** [comment]
Нет, если координаты не определены, блокировать не нужно.
Если описанный тобой вариант уже реализован, то отлично. Можно закрывать.
