### ISSUE TITLE
Если аппарат при фотографировании прописывает в EXIF данные об ориентации аппарата при съемке, то в галерее ориентировать фото по этим данным.

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/ngm_clink_monitoring#51]

**Comment by yellow-sky** [comment]
Никита, а есть возможность реально разворачивать их? например при сжатии?

**Comment by NikitaFeodonit** [comment]
> реально разворачивать их?

Так и сделал. Если аппарат пишет EXIF-тег ориентации при съемке, то он учитывается и фото разворачивается в соответствии с ним.
