### ISSUE TITLE
Не умещается надпись «Сохранять полноразмерные фото»

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#68]
![image](https://cloud.githubusercontent.com/assets/1277422/7045073/cf48d302-de02-11e4-9f57-3f60e77411d0.png)

**Comment by NikitaFeodonit** [comment]
Тут только изменение текста этой строки, чтобы он был не длиннее 20 символов.

**Comment by NikitaFeodonit** [comment]
Не могу придумать вариант.

**Comment by yellow-sky** [comment]
авто переноса строк нет?

2015-04-08 15:45 GMT+03:00 NikitaFeodonit notifications@github.com:

> Не могу придумать вариант.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/68#issuecomment-90903391
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
Это активити настроек, формируемое системой. Надо посмотреть.

**Comment by yellow-sky** [comment]
Может там есть автопрокрутка?

8 апреля 2015 г., 15:50 пользователь NikitaFeodonit <
notifications@github.com> написал:

> Это активити настроек, формируемое системой. Надо посмотреть.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/68#issuecomment-90904751
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
Нет, ничего не предусмотренно. Только в одну строку.

**Comment by NikitaFeodonit** [comment]
Или менять текст, или пользователю крутить экран в горизонтальное положение. Сам нередко это делаю в других программах.

**Comment by yellow-sky** [comment]
Ставим на паузу
