### ISSUE TITLE
Изменить надписи в форме настроек

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#69]
Сохранять полноразмерные фото -> Сохранять фото
Сохранять полноразмерные фото в папке с данными программы ->Сохранять фотографии в указанной папке

Папка с данными программы -> Папка для хранения фото

**Comment by NikitaFeodonit** [comment]
Это поменяет суть. Это действительно папка с данными программы, в которой есть папка с фото.

**Comment by NikitaFeodonit** [comment]
Правда, в той папке данных больше пока ничего нет.

**Comment by NikitaFeodonit** [comment]
> Переименовать «Папка с данными программы» на
> «Папка для хранения полноразмерных фото».

Если именно этот текст сделать, то не поместится, как и в #68.

**Comment by yellow-sky** [comment]
Новые вводные:
Сохранять фото [ ]

Папка для хранения фото
Пояснение ниже:
"Сохранять фотографии в указанной папке"

**Comment by NikitaFeodonit** [comment]
Нужно изменить соответственно сообщения в диалоге изменения папки.
