### ISSUE TITLE
Более интуитивное оповещение о синхронизации в GUI и панели

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#7]
Оповещение о процессе синхронизации необходимо сделать более явным и понятным.
Если приложение свернуто и процесс идет в бэкграунде, то необходимо показывать значек в панели - Данные синхронизируются. После окончания, значек должен смениться на Синхронизация завершена.
Аналогично данные операции должны быть отражены в интерфейсе пользователя (если программа не свернута).  
Возможно два эти значка и сообщение необходимо выводить в панели сверху (принимаются предложения как это лучше реализовать - всплывающие сообщения, значки и тд).

**Comment by NikitaFeodonit** [comment]
Добавил уведомления.

**Comment by NikitaFeodonit** [comment]
Добавил уведомления.
1) При старте синхронизации уведомление не убираемое, с прогрессбаром.
2) По окончании синхронизации или по ошибке уведомление убираемое.

Во всех случаях по щелчку на уведомлении открывается основная активность.

Сообщения, заголовки и иконки уведомлений тестовые.

Есть две иконки, маленькая и большая. Маленькая висит всё время в трее, пока есть уведомление, она же справа в окне уведомления. Она должна быть одноцветная, только белый цвет на прозрачном фоне.

Большая иконка может быть любой.

Принимаю предложения по оформлению уведомлений (иконки, текст). Так как оформление не доделано, не закрываю.

**Comment by yellow-sky** [comment]
Пока оставляем так. Ждем фидбека от клиента.

3 февраля 2015 г., 14:50 пользователь NikitaFeodonit <
notifications@github.com> написал:

> Добавил уведомления.
> 1) При старте синхронизации уведомление не убираемое, с прогрессбаром.
> 2) По окончании синхронизации или по ошибке уведомление убираемое.
> 
> Во всех случаях по щелчку на уведомлении открывается основная активность.
> 
> Сообщения, заголовки и иконки уведомлений тестовые.
> 
> Есть две иконки, маленькая и большая. Маленькая висит всё время в трее,
> пока есть уведомление, она же справа в окне уведомления. Она должна быть
> одноцветная, только белый цвет на прозрачном фоне.
> 
> Большая иконка может быть любой.
> 
> Принимаю предложения по оформлению уведомлений (иконки, текст). Так как
> оформление не доделано, не закрываю.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/7#issuecomment-72637780
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
Нужно будет поменять иконки, создадим новый issue. Этот закрываю.
