### ISSUE TITLE
Не перемещать фотографии из старой папки в новую

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#70]
Клиент хочет чтобы после выбора нового местоположения не было реального копирования данных, а просто поменялась папка. Старые данные удалять не нужно. 
Соответственно не нужно выводить предупреждение о том, что папка будет перемещена.

**Comment by NikitaFeodonit** [comment]
> Соответственно не нужно выводить предупреждение о том, что папка будет перемещена.

Это не предупреждение, а пояснение, что нужно сделать. Чтобы было понятно для непонятливых. Можно было бы просто изменить текст этого пояснения.

> Клиент хочет чтобы после выбора нового местоположения не было реального копирования данных, а просто поменялась папка. Старые данные удалять не нужно.

Что я понял:
1) При смене папки старые фото остаются на прежнем месте.
2) Новые добавляются в указанную новую папку.
Так?

**Comment by yellow-sky** [comment]
1. Пояснение все-таки убрать
2. Да, все верно

Контрол выбора директории возможно придется поменять

**Comment by NikitaFeodonit** [comment]
> Контрол выбора директории возможно придется поменять

Стандартного диалога выбора файла/папки нет. Я использовал стороннюю библиотеку, которых выбор весьма ограничен. А с возможностью выбора именно папки еще меньше.

Ту библиотеку я поправил под наш проект. Можно еще что в ней исправить. Но что именно нужно?

**Comment by NikitaFeodonit** [comment]
> Контрол выбора директории возможно придется поменять

Для этого лучше отдельный тикет.
