### ISSUE TITLE
Изменить подпись объектов в слоях

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#76]
В данный момент у нас выводится подпись:
XX - Название объекта
![screenshot_2015-04-08-17-12-11](https://cloud.githubusercontent.com/assets/1277422/7047062/cffc1272-de12-11e4-85db-546a09cb9437.png)
![screenshot_2015-04-08-17-10-23](https://cloud.githubusercontent.com/assets/1277422/7047067/d2200d06-de12-11e4-8d75-3018a5a71411.png)

Предлагается отказаться от номеров, и в случае если name пустое (null or string.strip()=='') 
то выводить "[Нет наименования]"
Если name не пустое, то выводить только его.

**Comment by NikitaFeodonit** [comment]
Если список объектов достаточно длинный, чтобы не поместиться на экран, то думаю, что без номеров будет достаточно сложно ориентироваться. Особенно, если все объекты без названия.

**Comment by yellow-sky** [comment]
Случай, когда нет названий - это экстраординарный. Названия должны быть. Но
если забыли прописать, то пусть пользователь видит, что что-то не так и
сообщит админу.

8 апреля 2015 г., 17:46 пользователь NikitaFeodonit <
notifications@github.com> написал:

> Если список объектов достаточно длинный, чтобы не поместиться на экран, то
> думаю, что без номеров будет достаточно сложно ориентироваться. Особенно,
> если все объекты без названия.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/76#issuecomment-90937616
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
Понял.
