### ISSUE TITLE
Переименовать название аккаунта в настройках Android

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#77]
Возможно ли переименовать 'NextGIS Web' в разделе Аккаунты системных настроек Android?
Например на "Компьюлинк Мониторинг"?

Если сложно\невозможно то не делаем. Если просто - то желательно переименовать.

**Comment by NikitaFeodonit** [comment]
Это не возможно, так как это вшито в библиотеку maplib. И все приложения, основанные на ней, в разделе аккаунтов с названием 'NextGIS Web' размещают свои аккаунты. То есть если дополнительно поставить NextGIS Mobile, то там будут и подключения, созданные в нем.
