### ISSUE TITLE
Новое окно выбора директории хранения фото

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#78]
1) Вариант когда окно выбора позволяет пройти в корень ФС - очень плохой. Все файловые браузеры показывают один\два диска (в зависимости от наличия вставленной sd), на которых пользователь может что-то сохранять. При этом приложения показывают какой из них внешний, какой внутренний. После выбора диска пользователь может проводить навигацию только внутри него. 
Нам нужно что-то подобное.

2) Если пункт один будет выполнен, то можно оставить как есть. Если нет - то нужна другая форма выбора папки, наподобие той, что есть в maplib_ui - выбор папки в зависимости от прав пользователей.  Но в той форме нет кнопки - создать папку. Её придется дополнять.

**Comment by NikitaFeodonit** [comment]
Мы же не файловый менеджер делаем. Стандартного диалога выбора файла/папки нет, а выбор сторонних библиотек весьма ограничен. А с возможностью выбора именно папки еще меньше, и тем меньше с возвожностью создания папки.

Поискать/подумать попробую еще, но делать нечто новое свое, думаю, было бы неразумно. Это отдельная программа-библиотека получится.

**Comment by NikitaFeodonit** [comment]
Сделал таки 1-й вариант.
