### ISSUE TITLE
Оформления для различных типов объектов на карте

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#79]
В данный момент у нас все объекты из всех слоев красятся одинаково.
Минимально необходимо:
- сделать различные оформления для слоев (описание оформления подготовлю)

Максимально:
- сделать оформление в зависимости от атрибутов объектов (статусов и типов)

**Comment by yellow-sky** [comment]
Оформление для муфт:
![image](https://cloud.githubusercontent.com/assets/1277422/7199779/07729ec6-e500-11e4-8869-58a7d262dec6.png)

**Comment by yellow-sky** [comment]
Оформления для кроссов:
![image](https://cloud.githubusercontent.com/assets/1277422/7202431/dbe56d4a-e51a-11e4-9f20-2ee34caf6b67.png)
сами правила:
![image](https://cloud.githubusercontent.com/assets/1277422/7202444/f466eda8-e51a-11e4-8619-24bd2ab534f0.png)

Так как оформление сложное, предлагаю сделать белый квадратик с черной окантовкой для проектируемых и не определенных, а для построенных - зеленый квадрат с черной окантовкой.

**Comment by yellow-sky** [comment]
Оформления для точек доступа:
![image](https://cloud.githubusercontent.com/assets/1277422/7202533/f69c5a94-e51b-11e4-9169-f82a2cb32dbe.png)
сами правила:
![image](https://cloud.githubusercontent.com/assets/1277422/7202544/0ddb19c0-e51c-11e4-81f9-14d06b472892.png)

**Comment by yellow-sky** [comment]
Точки А-Б:
![image](https://cloud.githubusercontent.com/assets/1277422/7202659/1bae459e-e51d-11e4-9d01-06b3cc122db0.png)
сами правила:
![image](https://cloud.githubusercontent.com/assets/1277422/7202679/3ad5d3ce-e51d-11e4-9314-a6f2234667f8.png)
Так как оформление сложное, предлагается использовать либо ромбик либо треугольник с разными цветами (красный и синий)

**Comment by yellow-sky** [comment]
Оформление для Длин ОК:
![image](https://cloud.githubusercontent.com/assets/1277422/7202761/e70f50de-e51d-11e4-9b2d-6e9c026718ec.png)
сами правила:
![image](https://cloud.githubusercontent.com/assets/1277422/7202774/fb1828f8-e51d-11e4-8ccf-d07ec459cae7.png)

**Comment by BishopGIS** [comment]
Для создания такого оформления нужно расширить класс стиля (https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/display/Style.java) своими классами.
1. Для векторных точек (п. 1 и 2) я бы модифицировал класс https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/display/SimpleMarkerStyle.java. Кружок там есть, осталось добавить квадратик с крестиком (MarkerStyleBoxPlusCross)
2. С маркерами - тут видимо отдельный стиль SimplePictureStyle надо делать
3. С линиями: https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/display/SimpleLineStyle.java
4. Вот для последнего стиля (линия с вопросиком) - тут надо отдельный стиль делать от  https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/display/Style.java. Внутри стиля будут "подстили" SimpleLineStyle + SimpleMarkerStyle - в отдельных переменных. А дальше вопросик гонишь вдоль линии.

**Comment by BishopGIS** [comment]
Теперь о правилах. Тут надо уже делать отдельный рендерер (RuleBasedFeatureRenderer) наследуя от этого: https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/display/Renderer.java по аналогии с этим: https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/display/SimpleFeatureRenderer.java

Суть там такая:
1. Внутри рендерера массив из идентификаторов геометрий и стилей который им соответствует: map<id, Style>
2. При отрисовке по идентификатору берется стиль и им и рисуется
3. При назначении стиля слою или при изменении слоя - карта (map<id, Style>) перезаполняется, ну или меняется стиль изменившейся записи.
4. Заполнение и назначение стилей согласно правилам.

**Comment by NikitaFeodonit** [comment]
> Точки А-Б:

А как для точки Б показывать измерено / неизмерено? Если, конечно, это нужно.

**Comment by NikitaFeodonit** [comment]
Справочники
https://gis.compulink.ru/resource/240

Справочник для laying_method
https://gis.compulink.ru/resource/2425

**Comment by yellow-sky** [comment]
в данный момент статус точек АБ ни как на карте не отображается. предлагаю и на мобильном этим не заниматься

**Comment by yellow-sky** [comment]
![image](https://cloud.githubusercontent.com/assets/1277422/14105038/bbc314d8-f5b1-11e5-9631-522ad2f00069.png)
