### ISSUE TITLE
Автосинхронизация должна быть включена по умолчанию

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#8]
Предполагается, что ручной синхронизацией пользователи не будут пользоваться. Все должно идти в атоматическом режиме.
Пункт Ручная синхронизация должна остаться только на период тестирования.

**Comment by NikitaFeodonit** [comment]
Какой должен быть период синхронизации?

**Comment by yellow-sky** [comment]
пока выставим 5ть минут

2015-02-09 18:53 GMT+03:00 NikitaFeodonit notifications@github.com:

> Какой должен быть период синхронизации?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/8#issuecomment-73532226
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
Давай 10, чтобы меньше переделывать. В maplibui сейчас это минимальный интервал, который можно выставить.

**Comment by yellow-sky** [comment]
ок

9 февраля 2015 г., 19:01 пользователь NikitaFeodonit <
notifications@github.com> написал:

> Давай 10, чтобы меньше переделывать. В maplibui сейчас это минимальный
> интервал, который можно выставить.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/ngm_clink_monitoring/issues/8#issuecomment-73533858
> .

## 

Best regards,

Nikulin Eugeny

**Comment by NikitaFeodonit** [comment]
> Пункт Ручная синхронизация должна остаться только на период тестирования.

Такой сценарий. Человек получил задание, добавил аккаунт. При добавлении сработала автосинхронизация, данные загрузились. Проверили, всё хорошо, уехали в поле.

Человек выполнил задание, получает новое. На сервере для того же его аккаунта для того же запроса обновили список слоев. На смартфоне аккаунт тот же. Нужно загрузить новые данные, которые загружаются также по синхронизации.

Без этого пункта меню придется лишний раз ждать те 10 минут, чтобы убедиться, что всё хорошо и можно ехать в поле. Думаю, что его нужно оставить.

**Comment by NikitaFeodonit** [comment]
> Без этого пункта меню придется лишний раз ждать те 10 минут, чтобы убедиться, что всё хорошо и можно ехать в поле. Думаю, что его нужно оставить.

Можно, конечно, запустить синхронизацию вручную через системные настройки -- Аккаунты -- NextGIS Web -- Compulink Account -- снять и поставить галку для нужного приложения (Compulink Monitoring) -- синхронизация запустится.

Но для людей, которые не слишком разбираются с компьютерной техникой, это может оказаться сложно.
