### ISSUE TITLE
Ошибка при синхронизации

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#80]
1. Выбираю тип работ «Монтаж точки доступа», далее п.Воронов Лог, затем точку доступа «01 – ТД п.Воронов Лог». 
2. Устанавливаю статус работ «Выполнено». 
3. Возвращаюсь на предыдущий экран, выбираю в меню «Синхронизировать». Пока все в порядке. 
4. Далее снова щелкаю по точке доступа «01 – ТД п.Воронов Лог»
5. снимаю статус «Выполнено»
6. Пункт меню «Синхронизировать» недоступен, т.к. еще выполняется предыдущая синхронизация
7. Дожидаюсь окончания и снова запуская синхронизацию

В результате статус самостоятельно возвращается в значение «Выполнено».

**Comment by NikitaFeodonit** [comment]
Проверю.

> Возвращаюсь на предыдущий экран, выбираю в меню «Синхронизировать».

Это делать необязательно, меню доступно из любого экрана.

**Comment by NikitaFeodonit** [comment]
На моей сборке не повторяется.

**Comment by NikitaFeodonit** [comment]
> Возвращаюсь на предыдущий экран, выбираю в меню «Синхронизировать».

По окончании синхронизации экран всегда обновляется, соответственно, и отображение статуса должно обновляться на актуальное, если было изменено на сервере.

**Comment by yellow-sky** [comment]
Стабильно воспроизводится.
Заметка:
1) Нужно обязательно переходить на предыдущий экран
2) При втором выходе на уровень выше необходимо открыть меню и ждать, пока не станет доступным пункт Синхронизация

**Comment by yellow-sky** [comment]
Кино снял :)
https://drive.google.com/file/d/0B8fD-l_uK4vFY1ZYT2tLSjJndXc/view?usp=sharing

**Comment by NikitaFeodonit** [comment]
После просмотра видео у себя смог повторить.

**Comment by yellow-sky** [comment]
Это хорошо
27.04.2015 11:10 пользователь "NikitaFeodonit" notifications@github.com
написал:

**Comment by NikitaFeodonit** [comment]
Закрыл через коммиты в maplib.
