### ISSUE TITLE
Не создается директория для фото по умолчанию

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#82]
Наблюдается следующая проблема в мобильном приложении. Я удалил и снова установил мобильное приложение на смартфоне. Никаких настроек не менял. При попытке сделать фото появляется сообщение об ошибке (см. скриншот ниже). Похоже данная проблема связана с отсутствием папки ngm_clink_monitoring на внутреннем накопителе. Если эту папку создать вручную, то ошибка больше не появляется.
![image](https://cloud.githubusercontent.com/assets/1277422/7613945/61b79ca0-f99c-11e4-8fee-4ffbead9f113.png)

Настройки сохранения фотографий:
![image](https://cloud.githubusercontent.com/assets/1277422/7613950/67aae2ac-f99c-11e4-909a-20aa759a2a4f.png)

**Comment by BishopGIS** [comment]
Это проблема от гугла тянется - приложение не везде может создавать папки (начиная с KitKat).
Лучше папку держать в android/data и т.д. на нужном накопителе. У нас есть в библиотеке чекала, что писать в папку можно.

**Comment by BishopGIS** [comment]
Вот еще может быть связано: https://github.com/nextgis/android_gisapp/issues/108

**Comment by NikitaFeodonit** [comment]
У меня на 4.4.4 (KitKat) не повторяется.

**Comment by NikitaFeodonit** [comment]
Забыл после удаления программы удалить саму папку. Теперь повторяется.

**Comment by NikitaFeodonit** [comment]
Проблема оказалась проще. Папка просто не создавалась в программе.

**Comment by NikitaFeodonit** [comment]
> Это проблема от гугла тянется - приложение не везде может создавать папки (начиная с KitKat).
> Лучше папку держать в android/data и т.д. на нужном накопителе.

Проблема такая: перед вызовом системной программы для фотографирования нужно создать временный пустой файл. Этот файл должен быть доступен и нашей программе, и системной, то есть двум сразу.

Как помню, начиная с KitKat, в системе есть ограничение безопастности, из-за которого файлы, созданные в приватных папках программы (android/data) не доступны другим программам.

Поэтому самым простым решением тут оказывается использовать общедоступные папки для временных файлов.

А в данной ситуации проблема получилась в том, что папка просто не создавалась в самой программе.
