### ISSUE TITLE
Строка с координатами

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#83]
В строке отображения координат текущего местоположения непонятно что означают 3-е и 4-ое число. Я догадываюсь, что это высота и точность определения координат. А другие пользователи как смогут об этом догадаться? Я предлагаю вообще не отображать значения высоты и точности, а также сделать подписи «Широта:» и «Долгота:».

![image](https://cloud.githubusercontent.com/assets/1277422/7614000/ab650efa-f99c-11e4-9b0e-f7974c71b09b.png)

**Comment by NikitaFeodonit** [comment]
По ТЗ (точнее, в "Требования к мобильному приложению ГИС v2") на форме они были нарисованы, но подписи мы решили убрать, https://github.com/nextgis/ngm_clink_monitoring/issues/16#issuecomment-72167626. Там же было обсуждение, почему высоту и точность оставили.

**Comment by yellow-sky** [comment]
Да, в требованиях есть. Но заказчик отказывается от них в пользу понятности.
13.05.2015 18:31 пользователь "NikitaFeodonit" notifications@github.com
написал:
