### ISSUE TITLE
Центрирование при переключении на карту 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#84]
При открытии карты должно происходить центрирование карты относительно текущего местоположения.

**Comment by NikitaFeodonit** [comment]
Теперь при открытии карты используются последние известные координаты.

Если после этого сдвинуть карту и нажать кнопку "Местоположение", то возможна ситуация, что в этот момент появится сообщение "Координаты не определены", так как по нажатии этой кнопки происходит попытка получить не последние известные координаты, а текущие, которые на данный момент действительно могут быть не определены.
