### ISSUE TITLE
Изменение надписи для Учетной записи

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#88]
На странице параметров учетной записи вместо надписи «Compulink Monitoring Acc..» выводить надпись «Компьюлинк Мониторинг», чтобы пользователь понимал, что это учетная запись приложения «Компьюлинк Мониторинг» и случайно ее не удалил. Или как вариант выводить надпись «Компьюлинк Мониторинг» вместо надписи NextGIS Web.
![image](https://cloud.githubusercontent.com/assets/1277422/7683388/782041e2-fd87-11e4-8dc9-a2f8d6183081.png)

**Comment by yellow-sky** [comment]
Это же вроде невозможно? был вроде такой тикет?

**Comment by NikitaFeodonit** [comment]
Это возможно, так как мы же в своей программе это и задаем. То есть просто поменять нужно. Только будет зависеть от локализации.

А вот "Или как вариант выводить надпись «Компьюлинк Мониторинг» место надписи NextGIS Web" -- это невозможно. Уже обсуждали в #77.

**Comment by yellow-sky** [comment]
Отлично. 
Тогда делаем:
вместо надписи «Compulink Monitoring Acc..» выводить надпись «Компьюлинк Мониторинг»

**Comment by NikitaFeodonit** [comment]
Там вообще-то «Compulink Monitoring Account» было, но не у всех показывается полностью.

**Comment by NikitaFeodonit** [comment]
Возможно изменить только на «Compulink Monitoring».

Если сделать в зависимости от локали, то при изменении локали программа не сможет работать с подключением, так как идентификация подключения происходит по имени подключения. И по другому не возможно.
