### ISSUE TITLE
 Муфты должны отображаться поверх строительных длин ОК

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#92]
На карте исправить порядок слоев.

**Comment by NikitaFeodonit** [comment]
Сейчас слои отображаются в порядке следования в пользовательском запросе. На тестовом сервере сейчас строительные длины 3-и по порядку.

Какой порядок должен быть для прочих слоев? На карте есть такие слои:

1) Строительные длины ОК
2) Оптические кроссы
3) Оптические муфты
4) Точки доступа

1-й остается первым, то есть нижним. Для 2-4 важен порядок?

**Comment by NikitaFeodonit** [comment]
Пока сделал только для "Строительные длины ОК". Если нужен будет иной порядок для остальных слоев, откроем новый тикет, этот закрываю.
