### ISSUE TITLE
В панели координат и удаленности пустые значения

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/ngm_clink_monitoring#95]
Почти всегда. Хотя фикс стабильный.
![screenshot_2015-06-26-14-30-48](https://cloud.githubusercontent.com/assets/1277422/8377379/871b300c-1c19-11e5-855c-f9d72ef2dc32.png)

**Comment by NikitaFeodonit** [comment]
Закрываю за ненадобностью из-за #96.
